services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 8080:80
    networks:
      - node-network
    depends_on:
      - app
      - db
  app:
    container_name: app
    build: ./src
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    networks:
      - node-network
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:5.7
    command: --init-file /data/application/init.sql
    restart: always
    tty: true
    volumes:
      - ./db/init.sql:/data/application/init.sql
      - ./db/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: "bridge"